apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
data:
  init-db.sql: |
    -- Criação de duas bases de dados
    CREATE DATABASE IF NOT EXISTS ledger;

    -- Criação de um usuário e concessão de privilégios
    GRANT ALL PRIVILEGES ON ledger.* TO 'admin'@'%';
    FLUSH PRIVILEGES;

    USE ledger;
    
    CREATE TABLE IF NOT EXISTS event(
        event_id varchar(50) primary key,
        correlation_id varchar(50) not null,
        org_id varchar(60) not null,
        processing_code varchar(100),
        program_id bigint not null,
        account_id bigint not null,
        description varchar(200) not null,
        producer varchar(100) not null,
        created_at timestamp,
        updated_at timestamp
    );

    CREATE TABLE IF NOT EXISTS entry(
        event_id varchar(50) not null,
        entry_type_id bigint not null,
        amount decimal(20, 15) not null,
        debit_account varchar(60),
        credit_account varchar(60),
        description varchar(200) not null,
        primary key(event_id, entry_type_id)
    );
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    com.job.service: mysql-db
    tier: mysql
spec:
  selector: 
    matchLabels:
      com.job.service: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels: 
        com.job.service: mysql-db
        tier: mysql
    spec:
      serviceAccountName: default
      containers:
        - name: mysql-db
          image: mysql
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: mysql-secrets
                   key: root
            - name: MYSQL_USER
              value: admin
            - name: MYSQL_PASSWORD
              valueFrom:
                 secretKeyRef:
                   name: mysql-secrets
                   key: accounting                   
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: mysql-initdb
          configMap:
            name: mysql-init-script    
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    com.job.service: mysql-service
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30001
  selector:
    com.job.service: mysql-db
    tier: mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pv-claim
  labels:
    com.job.service: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi