apiVersion: v1
kind: Service
metadata:
  name: ledger-events
  labels:
    com.job.service: ledger-events
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      nodePort: 31001
  selector:
    com.job.service: ledger-events
    tier: golang