// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package events is a generated GoMock package.
package events

import (
	context "context"
	reflect "reflect"

	scripts "github.com/clodoaldomarques/ledger-events/internal/domain/scripts"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// SaveEvent mocks base method.
func (m *MockRepository) SaveEvent(ctx context.Context, cid string, e Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveEvent", ctx, cid, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveEvent indicates an expected call of SaveEvent.
func (mr *MockRepositoryMockRecorder) SaveEvent(ctx, cid, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveEvent", reflect.TypeOf((*MockRepository)(nil).SaveEvent), ctx, cid, e)
}

// MockApi is a mock of Api interface.
type MockApi struct {
	ctrl     *gomock.Controller
	recorder *MockApiMockRecorder
}

// MockApiMockRecorder is the mock recorder for MockApi.
type MockApiMockRecorder struct {
	mock *MockApi
}

// NewMockApi creates a new mock instance.
func NewMockApi(ctrl *gomock.Controller) *MockApi {
	mock := &MockApi{ctrl: ctrl}
	mock.recorder = &MockApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApi) EXPECT() *MockApiMockRecorder {
	return m.recorder
}

// FindScriptByLevel mocks base method.
func (m *MockApi) FindScriptByLevel(ctx context.Context, cid, eventTypeID, orgID string, programID int64) (scripts.Script, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindScriptByLevel", ctx, cid, eventTypeID, orgID, programID)
	ret0, _ := ret[0].(scripts.Script)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindScriptByLevel indicates an expected call of FindScriptByLevel.
func (mr *MockApiMockRecorder) FindScriptByLevel(ctx, cid, eventTypeID, orgID, programID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindScriptByLevel", reflect.TypeOf((*MockApi)(nil).FindScriptByLevel), ctx, cid, eventTypeID, orgID, programID)
}

// MockTopic is a mock of Topic interface.
type MockTopic struct {
	ctrl     *gomock.Controller
	recorder *MockTopicMockRecorder
}

// MockTopicMockRecorder is the mock recorder for MockTopic.
type MockTopicMockRecorder struct {
	mock *MockTopic
}

// NewMockTopic creates a new mock instance.
func NewMockTopic(ctrl *gomock.Controller) *MockTopic {
	mock := &MockTopic{ctrl: ctrl}
	mock.recorder = &MockTopicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopic) EXPECT() *MockTopicMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockTopic) Emit(ctx context.Context, cid string, e Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Emit", ctx, cid, e)
	ret0, _ := ret[0].(error)
	return ret0
}

// Emit indicates an expected call of Emit.
func (mr *MockTopicMockRecorder) Emit(ctx, cid, e interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockTopic)(nil).Emit), ctx, cid, e)
}
